### ISSUE TITLE
OnChange Event

### ISSUE THREAD

**Issue by borhademohini** [Nelrohd/bootstrap-dropdown-checkbox#22]
Hello,

How would I fire onchange event for bootstrap dropdown checkbox.

**Comment by Treolorn** [comment]
$("#MonthsOfYear input[type='checkbox']").on("change", function () {
                console.log($("#MonthsOfYear").dropdownCheckbox("checked"));
            });
returned [] - with 1 selected item, [Object] - with 2 selected items
